[http]
listen = :8080

[sessions]
hashkey = 12345678901234567890123456789012
blockkey = 12345678901234567890123456789012

[clients]
internalsecret = internal_secret_2026

[backend]
allowall = false
backends = nextcloud

[nextcloud]
urls = http://nextcloud:80
secret = HPB_JWT_Secret_Key_2026_Nextcloud_Talk
skipverify = true

[nats]
url = nats://nats:4222

[grpc]
listen = :8081
